#we did this in the hopsworks jupyter

In [1]:
import hopsworks
import pandas as pd

In [2]:
project = hopsworks.login()

fs = project.get_feature_store()

2026-07-23 12:40:47,687 INFO: Python Engine initialized.

Logged in to project, explore it here https://eu-west.cloud.hopsworks.ai/p/42112

In [3]:
df = pd.read_csv(
    "features.csv",
    parse_dates=["datetime"]
)

df.head()

,datetime,us_aqi,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,temperature_2m,relative_humidity_2m,...,aqi_change,pm25_change,temperature_change,pressure_change,temp_humidity,wind_pm25,wind_pm10,target_day1,target_day2,target_day3
0,2022-08-07 00:00:00,143,97.3,139.7,2945.0,104.6,34.5,1.0,27.1,94,...,4.0,26.8,0.8,0.1,2547.4,214.06,307.34,136.0,151.0,154.0
1,2022-08-07 01:00:00,149,90.6,130.4,2508.0,91.3,32.2,21.0,26.5,94,...,6.0,-6.7,-0.6,0.9,2491.0,1612.68,2321.12,131.0,152.0,155.0
2,2022-08-07 02:00:00,151,76.8,110.6,1885.0,72.2,28.9,50.0,26.9,92,...,2.0,-13.8,0.4,0.5,2474.8,660.48,951.16,126.0,153.0,155.0
3,2022-08-07 03:00:00,152,59.3,85.2,1181.0,48.3,25.2,91.0,27.9,86,...,1.0,-17.5,1.0,0.5,2399.4,723.46,1039.44,123.0,154.0,156.0
4,2022-08-07 04:00:00,153,52.9,76.1,910.0,34.5,24.0,124.0,29.1,80,...,1.0,-6.4,1.2,0.0,2328.0,417.91,601.19,121.0,154.0,156.0

In [4]:
df.dtypes

datetime           datetime64[ns]
us_aqi                      int64
pm2_5                     float64
pm10                      float64
carbon_monoxide           float64
                        ...
wind_pm25                 float64
wind_pm10                 float64
target_day1               float64
target_day2               float64
target_day3               float64
Length: 72, dtype: object

In [5]:
print(df.shape)

(34632, 72)

In [6]:
df["datetime"].duplicated().sum()

np.int64(0)

In [7]:
feature_group = fs.get_or_create_feature_group(
    name="aqi_features",
    version=1,
    primary_key=["datetime"],
    description="AQI forecasting features"
)

In [8]:
feature_group.insert(
    df,
    wait=True
)

2026-07-23 12:42:11,066 WARNING: UserWarning: Casting timestamp column 'datetime' from 'ns' to 'us' will lose precision.

Feature Group created successfully, explore it at
https://eu-west.cloud.hopsworks.ai/p/42112/fs/30800/fg/51288

(None, None)

In [9]:
fg = fs.get_feature_group(
    name="aqi_features",
    version=1
)

In [10]:
data = fg.read()

data.head()

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (1.04s)

,datetime,us_aqi,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,temperature_2m,relative_humidity_2m,...,aqi_change,pm25_change,temperature_change,pressure_change,temp_humidity,wind_pm25,wind_pm10,target_day1,target_day2,target_day3
0,2022-08-07 00:00:00,143,97.3,139.7,2945.0,104.6,34.5,1.0,27.1,94,...,4.0,26.8,0.8,0.1,2547.4,214.06,307.34,136.0,151.0,154.0
1,2022-08-07 01:00:00,149,90.6,130.4,2508.0,91.3,32.2,21.0,26.5,94,...,6.0,-6.7,-0.6,0.9,2491.0,1612.68,2321.12,131.0,152.0,155.0
2,2022-08-07 02:00:00,151,76.8,110.6,1885.0,72.2,28.9,50.0,26.9,92,...,2.0,-13.8,0.4,0.5,2474.8,660.48,951.16,126.0,153.0,155.0
3,2022-08-07 03:00:00,152,59.3,85.2,1181.0,48.3,25.2,91.0,27.9,86,...,1.0,-17.5,1.0,0.5,2399.4,723.46,1039.44,123.0,154.0,156.0
4,2022-08-07 04:00:00,153,52.9,76.1,910.0,34.5,24.0,124.0,29.1,80,...,1.0,-6.4,1.2,0.0,2328.0,417.91,601.19,121.0,154.0,156.0

In [11]:
fg = fs.get_feature_group(
    name="aqi_features",
    version=1
)

df = fg.read()

Finished: Reading data from Hopsworks, using Hopsworks Feature Query Service (0.97s)

In [ ]:
X = df.drop(
    columns=[
        "datetime",
        "target_day1",
        "target_day2",
        "target_day3"
    ]
)

y = df[
    [
        "target_day1",
        "target_day2",
        "target_day3"
    ]
]